baseUrl: https://anderskingo.dk/
siteTitle: "Anders Kingo"
siteDescription: "Foredragsholder & Forfatter. Holder foredrag om Kierkegaard, Leonard Cohen og kristendom"
siteKeywords:
  - "Søren Kierkegaard"
  - "Foredrag"
  - "Teologi"
  - "Leonard Cohen"
