baseUrl: https://anderskingo.dk/foredrag/cohen
siteTitle: "Anders Kingo"
site_description: "Foredragsholder & Forfatter. Holder foredrag om Kierkegaard, Leonard Cohen og kristendom"
siteKeywords:
  - "Søren Kierkegaard"
  - "Foredrag"
  - "Teologi"
  - "Leonard Cohen"
