backend:
  # name: git-gateway
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: content/images
public_folder: images
collections:
  - name: meta
    label: Meta
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: "Webstedsindstillinger"
        file: "content/meta/config.yml"
        description: "Generelle webstedsindstillinger"
        fields:
          - name: "baseUrl"
            label: "Side link"
            widget: "string"
            hint: "Hjemmesidens webadresse"
          - name: "siteTitle"
            label: "Side titel"
            widget: "string"
          - name: "siteDescription"
            label: "Side beskrivelse"
            widget: "string"
          - name: "siteKeywords"
            label: "Keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
      - name: banner
        label: Banner
        file: "content/meta/banner.yml"
        description: "Banner tekst"
        fields:
          - label: "Overskrift"
            name: "header"
            widget: "string"
          - label: "Underhoved"
            name: "subheader"
            widget: string
      - name: footer
        label: Sidefod
        file: "content/meta/footer.yml"
        description: "Sidefod tekst"
        fields:
          - label: "Tekst"
            name: "text"
            widget: "string"

  - name: pages
    label: "Sider"
    folder: "content/pages"
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Billed", name: "image", widget: "image", required: false }

  - name: lectures
    label: Foredrag
    folder: "content/lectures"
    create: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Sti", name: "slug", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }
      - {
          label: "Billede",
          required: false,
          name: "image",
          widget: "image",
          hint: "Husk at udfylde beskrivelsen af billedet",
        }
      - {
          label: "Alternative oplysninger (billed)",
          default: "Billed tekst",
          name: "imageAlt",
          widget: "string",
          hint: "Denne tekst bliver brugt til folk, som ikke kan se billedet",
        }

  - name: travel-programs
    label: "Kulturrejse programmer"
    folder: "content/travel-programs"
    create: true
    extension: "mdx"
    format: "frontmatter"
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - label: "Dagsprogram"
        name: "daily-program"
        widget: list
        fields:
          - label: "Tekst"
            name: "text"
            widget: markdown
          - label: "Billede"
            name: "image"
            widget: image
            required: false
            hint: "Husk at udfylde beskrivelsen af billedet"
          - label: "Alternative oplysninger (billed)"
            default: "Billed tekst"
            name: "imageAlt"
            widget: "string"
            hint: "Denne tekst bliver brugt til folk, som ikke kan se billedet"
