backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: src/images
public_folder: images
collections:
  - name: meta
    label: Meta
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: "Webstedsindstillinger"
        file: "src/meta/config.yml"
        description: "Generelle webstedsindstillinger"
        fields:
          - name: "baseUrl"
            label: "Side link"
            widget: "string"
            hint: "Hjemmesidens webadresse"
          - name: "siteTitle"
            label: "Side titel"
            widget: "string"
          - name: "siteDescription"
            label: "Side beskrivelse"
            widget: "string"
          - name: "siteKeywords"
            label: "Keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
      - name: banner
        label: Banner
        file: "src/meta/banner.yml"
        description: "Banner tekst"
        fields:
          - label: "Overskrift"
            name: "header"
            widget: "string"
          - label: "Underhoved"
            name: "subheader"
            widget: string
      - name: footer
        label: Sidefod
        file: "src/meta/footer.yml"
        description: "Sidefod tekst"
        fields:
          - label: "Tekst"
            name: "text"
            widget: "string"

  - name: pages
    label: "Sider"
    folder: "src/pages"
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "tekst", name: "body", widget: "markdown" }

  - name: lectures
    label: Foredrag
    folder: "src/pages/foredrag"
    create: true
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: travels
    label: Kulturrejseprogrammer
    folder: "src/pages/kulturrejser"
    create: true
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: projects
    label: "Mine Projekter"
    folder: "src/pages/mine-projekter"
    create: true
    extension: "mdx"
    format: "frontmatter"
    summary: "{{title}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }
